name: ci

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  TAG: $(date +%s)

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TAG }}
