name: Release
on:
  push:
    tags:
      - 'v*'
env:
  IMAGE_NAME: adtrdr/json-server-app

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Verify image
        run: |
          docker image ls ${{ env.IMAGE_NAME }} --no-trunc

  release:
    name: Trigger argo deployment
    needs: docker-build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.event_name != 'pull_request' }}
    env:
      ARGOCD_ENV: gh-action-argocd-app-env
      WORKFLOW: deploy
      BRANCH: main
      PORT: 8000

    steps:
      - name: Add TAG_NAME env property
        run: |
          echo "TAG_NAME=`echo ${GITHUB_REF#refs/tags/}`" >> $GITHUB_ENV

      - name: Open PR in Environment Repository for new App Version
        uses: benc-uk/workflow-dispatch@v1.1
        env:
          ENV_REPO: ${{ github.event.repository.owner.name }}/${{ env.ARGOCD_ENV }}
        with:
          workflow: ${{ env.WORKFLOW }}
          # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{
            "tag_name":"${{ env.TAG_NAME }}",
            "app_repo":"${{ github.event.repository.name }}",
            "image":"${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}",
            "port":"${{ env.PORT }}
          }'
          ref: refs/heads/${{ env.BRANCH }}
          repo: ${{ env.ENV_REPO }}
